### ISSUE TITLE
Fix removing challenges causing an exception

### ISSUE THREAD

**Issue by iafb** [MCLD/gra4#10]
Calling UpdateSave when removing challenges tries to return the updated challenge but can't because the deleted flag is set to true

**Comment by ghost** [comment]
Your issue doesn't follow our guidelines. Please fix the following:

* Issue title must be in imperative, present tense \(e\.g\. "add", "fix", "change"\) [(?)](https://gitmagic.io/rules/#/issue/subject-must-be-in-tense)

[Click here](https://app.gitmagic.io/MCLD/gra4/10/1b2b5cb1-0b73-465b-b80c-d039e76f7ff5/d1708ce2-47ae-4bbd-bdf8-d395fcefdf6f) for details.

Thank you! :pray:
<sub>
This comment was made by [GitMagic](https://gitmagic.io/) – Magically enforcing your contribution guidelines.
</sub>

**Comment by ghost** [comment]
Your issue doesn't follow our guidelines. Please fix the following:

* Issue title must be in imperative, present tense \(e\.g\. "add", "fix", "change"\) [(?)](https://gitmagic.io/rules/#/issue/subject-must-be-in-tense)

[Click here](https://app.gitmagic.io/MCLD/gra4/10/1b2b5cb1-0b73-465b-b80c-d039e76f7ff5/2044dcde-9f90-46b0-b692-9fe2a2d42c72) for details.

Thank you! :pray:
<sub>
This comment was made by [GitMagic](https://gitmagic.io/) – Magically enforcing your contribution guidelines.
</sub>

**Comment by ghost** [comment]
Thank you, everything looks good now! :bowtie:

**Comment by k7hpn** [comment]
Call `ChallengeService.RemoveChallenge` to remove a challenge rather than using `UpdateSave`

**Comment by iafb** [comment]
`Challenge.RemoveChallenge` calls `RemoveSave` which calls `UpdateSave`
