### ISSUE TITLE
Deleting user history does not remove badges

### ISSUE THREAD

**Issue by justinmeiners** [MCLD/gra4#157]
If a user is awarded a badge, and then I remove the log that awarded it from their history, (in mission control) the badge is still shown on their dashboard.

## Steps to reproduce
1. In mission control select a user.
2. Select the history tab.
3. Delete a log awarding a badge.

## Expected behavior
Deleting the history of the event that awarded the badge should delete the badge.

This gets complicated, and is probably not desired if there are multiple ways the badge can be awarded (such as triggers etc) but right now it appears that badges are tied 1:1 with challenges. I noticed there is some code from triggers but it appears unused. Are badges going to return to being independent things such as in GRA 3?

## Actual behavior

Deleting the log event keeps the awarded badge on the users profile.

**Comment by k7hpn** [comment]
Trigger code is currently in development in [my triggers branch](https://github.com/haraldnagel/gra4/tree/triggers). As for the way it works: badges are awarded with two things:

- a row in `UserBadges`
- a row in `UserLogs`

As long as it's cleared in both locations we should be fine. In my triggers work I'm abstracting out to a single call (hopefully) for awarding badges, as long as we use that everywhere and ensure that removing badges follows the same logic then it shouldn't be a problem.

**Comment by k7hpn** [comment]
Just a note: I've opened PR #161 for the initial implementation of triggers.

**Comment by k7hpn** [comment]
This is a confirmed bug, removing a challenge from history does not remove the badge.
