### ISSUE TITLE
Add rudimentary dynamic avatar functionality

### ISSUE THREAD

**Issue by k7hpn** [MCLD/gra4#163]
Add rudimentary dynamic avatar functionality:
- Ability for users to construct a dynamic avatar using artwork included in the package

**Comment by justinmeiners** [comment]
Is the idea here similar to the multi part layers I created in GRA3 or did you have a different method in mind?

**Comment by k7hpn** [comment]
We are probably going to pull the avatar stuff out of GRA3 and plug it into GRA4 for now making whatever changes are necessary for it to work in ASP.NET Core. @iafb was working on extracting additional artwork and we have a plan to try to pull in nearly [all of the wardrobe artwork from Glitch/Eleven Giants](http://elevengiants.com/customize/index.html) eventually but not for this first milestone. In fact, we're probably not even going to have an admin interface for our first milestone since we need to have it available as soon as possible. We've also been tasked with having unlockable wardrobe items this year as well.

**Comment by justinmeiners** [comment]
Is this something that I could help out on? I would be happy to try implementing the avatars, using the stuff from GRA 3.

**Comment by k7hpn** [comment]
Sure! We were hoping to have the user side of it working by the 27th and we were just going to defer the admin side for now. I was going to call the class something like DynamicAvatar so people could switch between static and dynamic ones.

**Comment by justinmeiners** [comment]
If you are referring to the 27th of this month, you may not want to count on me. I *might* have it ready but since this will be my first time diving in I would hate for you to rely on me. Thoughts?

**Comment by k7hpn** [comment]
@justinmeiners I'm working on this, should have something by Monday

**Comment by justinmeiners** [comment]
@haraldnagel Oh I started working on this as well! However I started on the admin side. Later today I will commit my changes to my fork, if nothing is useful or it is a complete duplication of your work, that is completely fine, I will adopt yours. It will be a good introduction to the project regardless of if yours conflicts.

Edit: Actually I will get commit up soon so you can see where I am at.

**Comment by k7hpn** [comment]
I've been working on the user side. I have it working in a rudimentary sense but it still needs a little more work even on the user side.
