### ISSUE TITLE
Household enhancements (groups, aggregate functions)

### ISSUE THREAD

**Issue by k7hpn** [MCLD/gra4#164]
- Checkboxes next to member
- Remove pagination
- Ability to log minutes to checked members
  - Hard-code that it's minutes for now
  - Add issue about making this work properly
- Ability to log a secret code for checked members
- Mail icon which can be clicked to view mail
  - Greyed out if no mail
  - Exclaimation point (or similar) if they have mail
  - Can do "sign-in as" and then "show inbox" for now
- Add vendor code as last column
  - Can hard code it to be whatever we called book code in the database for now
  - Add issue about making this work properly
- Column order: Checkbox, Mail icon, Name/username, Points, Book code
- Change "Register member" to "Add username"

**Comment by iafb** [comment]
- Ability to add existing members to household from Mission Control (already exists on the user side)

**Comment by k7hpn** [comment]
I opened this as a new issue (#204) so we could close this issue out.
