### ISSUE TITLE
The Log file path is incorrect on non-windows platforms

### ISSUE THREAD

**Issue by justinmeiners** [MCLD/gra4#185]
## Description of issue
On my Mac the log file is created as "Logs\gra-20170225.txt". 

<img width="222" alt="screen shot 2017-02-25 at 12 43 14 pm" src="https://cloud.githubusercontent.com/assets/3220045/23334244/2d818d78-fb58-11e6-8900-8fe922648b12.png">

## Expected behavior
It appears the backslash should be interpreted is a directory so it should be a forward slash.

## Actual behavior
The filename has the folder path included.

**Comment by k7hpn** [comment]
Is this the latest code where the log file is configured in the appsettings.json? If it's in source we should be using Path to build the file path. If it's in the config I'm not sure how to fix.

**Comment by justinmeiners** [comment]
I am using the latest code. I did not try to dig into the cause at all, I just noticed the filename.
