### ISSUE TITLE
Modal task window "Cancel" button does not function properly

### ISSUE THREAD

**Issue by k7hpn** [MCLD/gra4#20]
In Mission Control, once opening a task details page, clicking "Cancel" results in a blank page with this url:
```
http://localhost:3033/MissionControl/Challenge/CloseTask/
```
## Steps to reproduce
1. In Mission Control, view a Challenge
2. Select a task to view it
3. Select the "Cancel" button

## Expected behavior
Modal pop-up disappears

## Actual behavior
Redirection to `http://localhost:3033/MissionControl/Challenge/CloseTask/`

**Comment by ghost** [comment]
Your issue doesn't follow our guidelines. Please fix the following:

* Issue title must be in imperative, present tense \(e\.g\. "add", "fix", "change"\) [(?)](https://gitmagic.io/rules/#/issue/subject-must-be-in-tense)

[Click here](https://app.gitmagic.io/MCLD/gra4/20/1b2b5cb1-0b73-465b-b80c-d039e76f7ff5/292e6702-29e4-4cd8-b05c-618cc52cca01) for details.

Thank you! :pray:
<sub>
This comment was made by [GitMagic](https://gitmagic.io/) – Magically enforcing your contribution guidelines.
</sub>

**Comment by ghost** [comment]
Thank you, everything looks good now! :bowtie:
