### ISSUE TITLE
Allow Challenge Codes to be limited by program, etc

### ISSUE THREAD

**Issue by justinmeiners** [MCLD/gra4#228]
In Challenges, one can either setup a "secret code", or a set of "requirements". Currently the "Limit to System, branch, program" option is only available for requirements . Would it be a pain to allow secret codes to be restricted by program, etc  as well?

Here is an example use case, our library might hold an event specifically for the children's program. At the event, the attendants would receive a code, but this code would just be for the kids. We would not want adults using it to get rewards which are not for them.

**Comment by k7hpn** [comment]
This makes sense, it would be ideal if this was a feature we could toggle on and off because some libraries (e.g. ours) probably won't ever want this (we discussed it and decided that it was too complicated to explain to customers that their kid could get points for a code but they could not).

**Comment by iafb** [comment]
A way it could be done at the moment is to create a secret code that everyone can use and then create a second trigger that's limited by program and requires the secret code's badge.

It's hard to have secret codes be limited and not be confusing to users as to why the codes they found didn't work. It's especially confusing on the household page where you may be applying it to multiple people and only some of them are eligible to redeem the code.

**Comment by justinmeiners** [comment]
@iafb Thank you. As long as there is "a way" to do it I don't think it needs to be the standard. I will follow that method you described.

**Comment by k7hpn** [comment]
Are we good to close this, then? The documented method will be as @iafb stated above?

**Comment by k7hpn** [comment]
I'm going to close since I think we have a workaround. We should probably document this but the documentation situation is nonexistent for 4.0 right now.
