### ISSUE TITLE
Deleted users stay logged in

### ISSUE THREAD

**Issue by iafb** [MCLD/gra4#276]
When deleted a user who is logged in can still access the site. They are still able to make some changes to things and will cause exceptions to be thrown.

**Comment by k7hpn** [comment]
An approach for this could be:

1. Set a global cache value indicating when/if a user was deleted (e.g. this could be a counter that starts at 0 when the site starts up)
2. In the login process, make a note of that global cache value in the session
3. When a user is deleted, update that global cache value (in the case of a counter, just increment it)
4. On page load, check the cached value and the session value - if they differ, the current user should be validated to still have an account (this would trigger item 2 above to happen again)

**Comment by iafb** [comment]
This issue can also come up when a head of household is signed in as a member of their household and someone adds the head of household to a different household causing them to no longer be a head of household with their ActiveUserId still being set to a household member.
