### ISSUE TITLE
Point Translations should not have an ActivityAmount

### ISSUE THREAD

**Issue by justinmeiners** [MCLD/gra4#285]
In ActivityServe.cs line 124, the point translation method is:

`int pointsEarned = (activityAmountEarned / translation.ActivityAmount) * translation.PointsEarned;`

If the point translation is setup so that it requires more than 1 of an activity to earn a point, than any entry less that will be ignored. For example, last year we setup 15 minutes of reading to equal one point. Any user who's entry was less than 15 minutes was silently ignored. Thus a user who enters 3 entries of 10 minutes got nothing, when they should have received 2 points.

Both users and administrators expect the accounting to be correct. For this reason, I think `translation.ActivityAmount` should be removed, leaving only `translation.PointsEarned`.

**Comment by ghost** [comment]
Your issue doesn't follow our guidelines. Please fix the following:

* Issue title must not end with a dot [(?)](https://gitmagic.io/rules/#/issue/subject-must-not-end-with-dot)

[Click here](https://app.gitmagic.io/MCLD/gra4/285/1b2b5cb1-0b73-465b-b80c-d039e76f7ff5/72d2e55d-9846-4f38-a0f7-4a58b230bc6a) for details.

Thank you! :pray:
<sub>
This comment was made by [GitMagic](https://gitmagic.io/) – Magically enforcing your contribution guidelines.
</sub>

**Comment by ghost** [comment]
Thank you, everything looks good now! :bowtie:
