### ISSUE TITLE
Joining/adding participants should be consolidated

### ISSUE THREAD

**Issue by justinmeiners** [MCLD/gra4#286]
The following controllers are essentially the same code, copy-pasted with minor tweaks:
- Single Page Joining
- Adding Household Member
- Mission Control Add Participant
- Mission Control Add Household Member
- Mission Control Edit Participant
- Edit Profile

Making changes to these is very difficult because each have quite a bit of code that does essentially the same thing. At worst,  this could be refactored into a partial view with some configuration options that would allow it to handle most, if not all cases. At best, there should be some controller or service which replaces the view and code for all of these.

I discussed this a bit with @iafb on my branch.

**Comment by k7hpn** [comment]
This is a worthy thing to try to fix, there's no need for us to have the same view and same validation code all over the place.
