### ISSUE TITLE
Household family entry doesn't seem to fit with point translations

### ISSUE THREAD

**Issue by justinmeiners** [MCLD/gra4#313]
The household has a feature which allows users to enter minutes read for the entire family, however since each program could be using different point translations, (some books read, some minutes read, etc) it doesn't seem to make sense.

How can it account for all these entry forms?

Side Note: Point entry appears to be similar to signup where there are about 5 different implementations spread out across mission control, household, individual page, etc.

**Comment by k7hpn** [comment]
You're right. It seems like maybe if any family member is in a program with a different point translation perhaps we should hide the ability to add points.

There are different locations for entering points but I believe the logic for handling point entry is centralized in one service, so at least there's that? 😞
