### ISSUE TITLE
If an error occurs parsing the appsettings.json, it will not be logged

### ISSUE THREAD

**Issue by justinmeiners** [MCLD/gra4#332]
Since the app json is loaded earlier than anything else in startup.cs, the program will fail silently if there is a syntax error. (On IIS)

**Comment by k7hpn** [comment]
This is a good point. Not sure in the context of Kestrel working with IIS how to best show an error other than having it output details via `stdout` and [having users enable `stdout` logging](https://docs.microsoft.com/en-us/aspnet/core/publishing/iis#troubleshooting-tips). Certainly a good idea if we can figure out a way to make it work.
