### ISSUE TITLE
Ability to return messages from Domain to Controller

### ISSUE THREAD

**Issue by iafb** [MCLD/gra4#446]

**Comment by ghost** [comment]
Your issue doesn't follow our guidelines. Please fix the following:

* Issue description cannot be empty [(?)](https://gitmagic.io/rules/#/issue/body-cannot-be-empty)

[Click here](https://app.gitmagic.io/MCLD/gra4/446/1b2b5cb1-0b73-465b-b80c-d039e76f7ff5/20e70b47-77b2-4d5c-ac9a-3550a3e71701) for details.

Thank you! :pray:
<sub>
This comment was made by [GitMagic](https://gitmagic.io/) – Magically enforcing your contribution guidelines.
</sub>

**Comment by ghost** [comment]
Your issue doesn't follow our guidelines. Please fix the following:

* Issue description cannot be empty [(?)](https://gitmagic.io/rules/#/issue/body-cannot-be-empty)

[Click here](https://app.gitmagic.io/MCLD/gra4/446/1b2b5cb1-0b73-465b-b80c-d039e76f7ff5/20e70b47-77b2-4d5c-ac9a-3550a3e71701) for details.

Thank you! :pray:
<sub>
This comment was made by [GitMagic](https://gitmagic.io/) – Magically enforcing your contribution guidelines.
</sub>

**Comment by iafb** [comment]
Added in #452
