### ISSUE TITLE
Handle database changes in POSTs as a single transaction

### ISSUE THREAD

**Issue by iafb** [MCLD/gra4#447]
Change database changes to be done in a single transaction so that if one part fails none of the changes will be saved.

**Comment by k7hpn** [comment]
@iafb Did we determine that this is being done thanks to the way the repository is configured and with Entity Framework? Do you have any idea which specific area this issue was in reference to?

**Comment by iafb** [comment]
We determined that it would be possible to do it however at the moment each repository call is saving the changes itself instead of queuing up all the changes and saving them all at once.

This wasn't in reference to any specific issue, was for a general case of how data should be handled to ensure database changes happen as expected.
