### ISSUE TITLE
Add position when adding challenge tasks in repository

### ISSUE THREAD

**Issue by iafb** [MCLD/gra4#9]
When adding a challenge task, the position should always be set to the last position in the list.

**Comment by ghost** [comment]
Your issue doesn't follow our guidelines. Please fix the following:

* Issue description cannot be empty [(?)](https://gitmagic.io/rules/#/issue/body-cannot-be-empty)

[Click here](https://app.gitmagic.io/MCLD/gra4/9/1b2b5cb1-0b73-465b-b80c-d039e76f7ff5/7b0631c7-ada0-40aa-8d9b-0db0d71c51b9) for details.

Thank you! :pray:
<sub>
This comment was made by [GitMagic](https://gitmagic.io/) – Magically enforcing your contribution guidelines.
</sub>

**Comment by ghost** [comment]
Your issue doesn't follow our guidelines. Please fix the following:

* Issue description cannot be empty [(?)](https://gitmagic.io/rules/#/issue/body-cannot-be-empty)

[Click here](https://app.gitmagic.io/MCLD/gra4/9/1b2b5cb1-0b73-465b-b80c-d039e76f7ff5/7b0631c7-ada0-40aa-8d9b-0db0d71c51b9) for details.

Thank you! :pray:
<sub>
This comment was made by [GitMagic](https://gitmagic.io/) – Magically enforcing your contribution guidelines.
</sub>

**Comment by ghost** [comment]
Thank you, everything looks good now! :bowtie:
